export const MODELS = {
  fast:               { id: "qwen/qwen3-next-80b-a3b-instruct" },
  reasoner:           { id: "deepseek/deepseek-r1-0528" },
  analyst:            { id: "qwen/qwen3-235b-a22b" },
  broad:              { id: "nvidia/nemotron-3-super-120b-a12b" },
  critic:             { id: "meta-llama/llama-3.3-70b-instruct" },
  wild:               { id: "arcee-ai/trinity-large-preview" },
  coder:              { id: "qwen/qwen3-coder" },
  threePhaseDirector: { id: "x-ai/grok-4.20-beta" },
  threePhaseArchitect:{ id: "deepseek/deepseek-r1-distill-llama-70b" },
  threePhaseWorker:   { id: "x-ai/grok-4.1-fast" },
  researchFrame:      { id: "x-ai/grok-4.20-beta" },
  researchSwarm:      { id: "x-ai/grok-4.1-fast" },
  researchFilter:     { id: "deepseek/deepseek-r1-distill-llama-70b" },
  researchSynthesize: { id: "x-ai/grok-4.20-beta" },
} as const;
